### ISSUE TITLE
Port helpers/embeds.py

### ISSUE THREAD

**Issue by net-tech** [vrnavi/refrigerator#6]
Hi there,

The `sv_config` cog is unable to load because it imports `helpers/embeds.py` which imports Discord and makes a Discord embed on line https://github.com/vrnavi/refrigerator/blob/d7f0ac43e16db7bd48af691e18eca622ef5c51a9/refrigerator/helpers/embeds.py#L86.

Is this intentional or has the helper module just not been ported.

**Comment by CominAtYou** [comment]
That most definitely is not intentional - the import for embeds.py was supposed to have been removed from sv_config when it was originally ported. Thanks for pointing it out.
